// MUST MATCH WITH /backend/types/ErrorCode.ts
export const ErrorCode = {
    // AUTH
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    FORBIDDEN: "FORBIDDEN",

    // RESOURCE
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",

    // VALIDATION
    INVALID_FORMAT: "INVALID_FORMAT",
    VALIDATION_FAILED: "VALIDATION_FAILED",

    // SERVER
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    AI_FAILURE: "AI_UNAVAILABLE",
    TOKEN_GENERATION_FAILED: "TOKEN_GENERATION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
