export enum ErrorType {
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    FORBIDDEN = "FORBIDDEN",

    NOT_FOUND = "NOT_FOUND",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",

    AUTH = "AUTH",
    VALIDATION = "VALIDATION",
    SERVER = "SERVER",
    NETWORK = "NETWORK",
    UNKNOWN = "UNKNOWN",
}
